group 'com.salesforce.marketingcloud.sfmc'
version '1.0-SNAPSHOT'

buildscript {
    ext.kotlin_version = '1.9.10'
    ext.r8_version = '8.2.42' 
    ext.marketingcloud_sdk_version = '9.0.+'
    ext.compile_sdk_version = 34
    ext.min_sdk_version = 21
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:8.1.4'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
        maven { url "https://salesforce-marketingcloud.github.io/MarketingCloudSDK-Android/repository" }
    }
}

apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'

android {
    compileSdkVersion compile_sdk_version

    namespace 'com.salesforce.marketingcloud.sfmc'

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = '17'
    }

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    defaultConfig {
        minSdkVersion min_sdk_version
    }

    dependencies {
        implementation "com.salesforce.marketingcloud:marketingcloudsdk:$marketingcloud_sdk_version"
    }
}

gradle.projectsEvaluated {
    // Disable Dokka tasks (causing ASM9 error)
    tasks.findAll { it.name.toLowerCase().contains("dokka") }.each { t ->
        t.enabled = false
    }
    // For javadoc tasks, create an empty jar if needed so publication doesn't fail
    tasks.findAll { it.name.toLowerCase().contains("javadoc") }.each { t ->
        t.enabled = false
        t.doLast {
            def outputFile = null
            if (t.hasProperty('archivePath')) {
                outputFile = t.archivePath
            } else if (t.hasProperty('destinationDir') && t.hasProperty('archiveName')) {
                outputFile = new File(t.destinationDir, t.archiveName)
            }
            if (outputFile != null && !outputFile.exists()) {
                outputFile.parentFile.mkdirs()
                ant.jar(destfile: outputFile)
            }
        }
    }
    // Also, create the expected debug-javadoc.jar if it doesn't exist (for publication)
    def debugJavadocJarPath = file("${buildDir}/intermediates/java_doc_jar/debug/debug-javadoc.jar")
    if (!debugJavadocJarPath.exists()) {
        debugJavadocJarPath.parentFile.mkdirs()
        ant.jar(destfile: debugJavadocJarPath)
    }
    // Also, create the expected release-javadoc.jar if it doesn't exist (for publication)
    def releaseJavadocJarPath = file("${buildDir}/intermediates/java_doc_jar/release/release-javadoc.jar")
    if (!releaseJavadocJarPath.exists()) {
        releaseJavadocJarPath.parentFile.mkdirs()
        ant.jar(destfile: releaseJavadocJarPath)
    }
}